apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name | default "default-release" }}-socks-ingress
  namespace: dev
  labels:
    {{ toYaml .Values.ingress.labels | indent 4 }}
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:471744311643:certificate/a230a5d9-f1c9-4e21-b87e-4ad4ec11901e"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/load-balancer-attributes: |
      deletion_protection.enabled=false
spec:
  ingressClassName: alb  # Correctement plac√© sous spec, pas dans les rules
  rules:
  - host: datascientets-socks-shop.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80
  - host: www.datascientets-socks-shop.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80
  - host: metrics.datascientets-socks-shop.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-release-grafana
            port:
              number: 80


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   labels:
# {{ toYaml .Values.ingress.labels | indent 4 }}
#   name: {{ .Release.Name }}-socks-ingress
#   annotations:
# {{ toYaml .Values.ingress.annotations | indent 4 }}
# spec:
#   ingressClassName: {{ .Values.ingress.ingressClassName }}
#   rules:
#   - host: {{ .Values.ingress.host }}
#     http:
#       paths:
#       - backend:
#           service:
#             name: front-end
#             port:
#               number: 80
#         path: /
#         pathType: Prefix
#   {{- if .Values.ingress.tlsSecretName }}
#   tls:
#   - secretName: {{ .Values.ingress.tlsSecretName }}
#     hosts:
#     - {{ .Values.ingress.host }}
#   {{- end }}
